import type { InventoryItem } from "@/types/item"

export const SHOP_ITEMS: InventoryItem[] = [
  {
    id: "sword",
    name: "Меч",
    icon: "https://cdn-icons-png.flaticon.com/512/1660/1660899.png",
    weight: 5,
    quantity: 0,
  },
  {
    id: "axe",
    name: "Топор",
    icon: "https://cdn-icons-png.flaticon.com/512/236/236719.png",
    weight: 6,
    quantity: 0,
  },
  {
    id: "bow",
    name: "Лук",
    icon: "https://cdn-icons-png.flaticon.com/512/3082/3082032.png",
    weight: 3,
    quantity: 0,
  },
  {
    id: "arrow",
    name: "Стрела",
    icon: "https://cdn-icons-png.flaticon.com/512/616/616408.png",
    weight: 0.1,
    quantity: 0,
  },
  {
    id: "dagger",
    name: "Кинжал",
    icon: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
    weight: 2,
    quantity: 0,
  },

  {
    id: "shield",
    name: "Щит",
    icon: "https://cdn-icons-png.flaticon.com/512/1087/1087010.png",
    weight: 7,
    quantity: 0,
  },
  {
    id: "helmet",
    name: "Шлем",
    icon: "https://cdn-icons-png.flaticon.com/512/616/616430.png",
    weight: 4,
    quantity: 0,
  },
  {
    id: "armor",
    name: "Броня",
    icon: "https://cdn-icons-png.flaticon.com/512/616/616404.png",
    weight: 12,
    quantity: 0,
  },
  {
    id: "boots",
    name: "Сапоги",
    icon: "https://cdn-icons-png.flaticon.com/512/1046/1046751.png",
    weight: 3,
    quantity: 0,
  },
  {
    id: "gloves",
    name: "Перчатки",
    icon: "https://cdn-icons-png.flaticon.com/512/1046/1046750.png",
    weight: 1,
    quantity: 0,
  },

  {
    id: "potion",
    name: "Зелье здоровья",
    icon: "https://cdn-icons-png.flaticon.com/512/590/590685.png",
    weight: 0.5,
    quantity: 0,
  },
  {
    id: "mana_potion",
    name: "Зелье маны",
    icon: "https://cdn-icons-png.flaticon.com/512/590/590682.png",
    weight: 0.5,
    quantity: 0,
  },
  {
    id: "bread",
    name: "Хлеб",
    icon: "https://cdn-icons-png.flaticon.com/512/1046/1046786.png",
    weight: 0.3,
    quantity: 0,
  },
  {
    id: "meat",
    name: "Мясо",
    icon: "https://cdn-icons-png.flaticon.com/512/3075/3075977.png",
    weight: 0.6,
    quantity: 0,
  },
  {
    id: "fish",
    name: "Рыба",
    icon: "https://cdn-icons-png.flaticon.com/512/3075/3075974.png",
    weight: 0.5,
    quantity: 0,
  },
  {
    id: "apple",
    name: "Яблоко",
    icon: "https://cdn-icons-png.flaticon.com/512/415/415682.png",
    weight: 0.2,
    quantity: 0,
  },
  {
    id: "cheese",
    name: "Сыр",
    icon: "https://cdn-icons-png.flaticon.com/512/3075/3075969.png",
    weight: 0.25,
    quantity: 0,
  },

  {
    id: "scroll",
    name: "Свиток",
    icon: "https://cdn-icons-png.flaticon.com/512/227/227940.png",
    weight: 0.2,
    quantity: 0,
  },
  {
    id: "ring",
    name: "Кольцо",
    icon: "https://cdn-icons-png.flaticon.com/512/589/589708.png",
    weight: 0.05,
    quantity: 0,
  },
  {
    id: "gem",
    name: "Кристалл",
    icon: "https://cdn-icons-png.flaticon.com/512/2107/2107845.png",
    weight: 0.1,
    quantity: 0,
  },
]
